### ISSUE TITLE
target object on method definition is ignored

### ISSUE THREAD

**Issue by julian-berbel** [mumuki/mulang-ruby#20]
Today a student sent the following solution on an exercise:
```ruby
class Notebook
  def initialize
    @bateria = 100
  end 
  def Notebook.utilizar! (minutos)
    @bateria =  @bateria - minutos
  end
  def cargar_a_tope!
    @bateria = 100
  end
end
```

rather than a class method, they were supposed to define `utilizar!` as an instance method of `Notebook`.

This caused trouble later since the correct solution (the same but without the `Notebook` target in `utilizar!` was being parsed to the same as the piece of code above.

**Comment by flbulgarelli** [comment]
Depends on https://github.com/mumuki/mulang/issues/174
