### ISSUE TITLE
No funciona el expectation de herencia en ruby

### ISSUE THREAD

**Issue by ArielUmansky** [mumuki/mulang-ruby#4]
Esta es la configuración:

![image](https://user-images.githubusercontent.com/1649905/34343536-0e0ad2e4-e9b2-11e7-88c6-fec2e9ddd442.png)

Este es el código:

```ruby
class AsambleaTest 
end
```
(el problema es que el ejercicio da verde)

FYI: El `::` no es el problema ya que no funcionó incluso sin indicar namespaces. Tampoco funciona correctamente el `Inherits` (sin el `:`)

**Comment by julian-berbel** [comment]
El problema es que es un ejercicio de Minitest, no de ruby, y minitest no tiene soporte para expectativas.

Sería bueno resolver el issue mumuki/mumukit#68 para evitar este problema.
